// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_structures.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createJobStructure = `-- name: CreateJobStructure :one
INSERT INTO job_structures (job_id, template_id, custom_name, quantity, unit_price, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, template_id, custom_name, quantity, unit_price, status, notes, created_at, updated_at
`

type CreateJobStructureParams struct {
	JobID      uuid.UUID      `json:"job_id"`
	TemplateID uuid.NullUUID  `json:"template_id"`
	CustomName sql.NullString `json:"custom_name"`
	Quantity   int32          `json:"quantity"`
	UnitPrice  sql.NullString `json:"unit_price"`
	Notes      sql.NullString `json:"notes"`
}

// Adds a structure to a job, optionally referencing a template.
func (q *Queries) CreateJobStructure(ctx context.Context, arg CreateJobStructureParams) (JobStructure, error) {
	row := q.db.QueryRowContext(ctx, createJobStructure,
		arg.JobID,
		arg.TemplateID,
		arg.CustomName,
		arg.Quantity,
		arg.UnitPrice,
		arg.Notes,
	)
	var i JobStructure
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TemplateID,
		&i.CustomName,
		&i.Quantity,
		&i.UnitPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobStructure = `-- name: DeleteJobStructure :exec
DELETE FROM job_structures WHERE id = $1
`

// Permanently deletes a job structure.
func (q *Queries) DeleteJobStructure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJobStructure, id)
	return err
}

const getJobStructure = `-- name: GetJobStructure :one
SELECT js.id, js.job_id, js.template_id, js.custom_name, js.quantity, js.unit_price, js.status, js.notes, js.created_at, js.updated_at, st.name AS template_name
FROM job_structures js
LEFT JOIN structure_templates st ON st.id = js.template_id
WHERE js.id = $1
`

type GetJobStructureRow struct {
	ID           uuid.UUID          `json:"id"`
	JobID        uuid.UUID          `json:"job_id"`
	TemplateID   uuid.NullUUID      `json:"template_id"`
	CustomName   sql.NullString     `json:"custom_name"`
	Quantity     int32              `json:"quantity"`
	UnitPrice    sql.NullString     `json:"unit_price"`
	Status       JobStructureStatus `json:"status"`
	Notes        sql.NullString     `json:"notes"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	TemplateName sql.NullString     `json:"template_name"`
}

// Retrieves a single job structure by ID.
func (q *Queries) GetJobStructure(ctx context.Context, id uuid.UUID) (GetJobStructureRow, error) {
	row := q.db.QueryRowContext(ctx, getJobStructure, id)
	var i GetJobStructureRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TemplateID,
		&i.CustomName,
		&i.Quantity,
		&i.UnitPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateName,
	)
	return i, err
}

const listJobStructures = `-- name: ListJobStructures :many
SELECT js.id, js.job_id, js.template_id, js.custom_name, js.quantity, js.unit_price, js.status, js.notes, js.created_at, js.updated_at, st.name AS template_name
FROM job_structures js
LEFT JOIN structure_templates st ON st.id = js.template_id
WHERE js.job_id = $1
ORDER BY js.created_at
`

type ListJobStructuresRow struct {
	ID           uuid.UUID          `json:"id"`
	JobID        uuid.UUID          `json:"job_id"`
	TemplateID   uuid.NullUUID      `json:"template_id"`
	CustomName   sql.NullString     `json:"custom_name"`
	Quantity     int32              `json:"quantity"`
	UnitPrice    sql.NullString     `json:"unit_price"`
	Status       JobStructureStatus `json:"status"`
	Notes        sql.NullString     `json:"notes"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	TemplateName sql.NullString     `json:"template_name"`
}

// Retrieves all structures for a given job, with template names.
func (q *Queries) ListJobStructures(ctx context.Context, jobID uuid.UUID) ([]ListJobStructuresRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobStructures, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobStructuresRow{}
	for rows.Next() {
		var i ListJobStructuresRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.TemplateID,
			&i.CustomName,
			&i.Quantity,
			&i.UnitPrice,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStructure = `-- name: UpdateJobStructure :one
UPDATE job_structures
SET template_id = $2, custom_name = $3, quantity = $4, unit_price = $5, status = $6, notes = $7
WHERE id = $1
RETURNING id, job_id, template_id, custom_name, quantity, unit_price, status, notes, created_at, updated_at
`

type UpdateJobStructureParams struct {
	ID         uuid.UUID          `json:"id"`
	TemplateID uuid.NullUUID      `json:"template_id"`
	CustomName sql.NullString     `json:"custom_name"`
	Quantity   int32              `json:"quantity"`
	UnitPrice  sql.NullString     `json:"unit_price"`
	Status     JobStructureStatus `json:"status"`
	Notes      sql.NullString     `json:"notes"`
}

// Updates fields on an existing job structure.
func (q *Queries) UpdateJobStructure(ctx context.Context, arg UpdateJobStructureParams) (JobStructure, error) {
	row := q.db.QueryRowContext(ctx, updateJobStructure,
		arg.ID,
		arg.TemplateID,
		arg.CustomName,
		arg.Quantity,
		arg.UnitPrice,
		arg.Status,
		arg.Notes,
	)
	var i JobStructure
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TemplateID,
		&i.CustomName,
		&i.Quantity,
		&i.UnitPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
