// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (customer_id, job_number, status, expected_completion, expected_delivery, total_price, notes)
VALUES ($1, 'KW-' || LPAD(nextval('job_number_seq')::text, 4, '0'), $2, $3, $4, $5, $6)
RETURNING id, customer_id, job_number, status, expected_completion, expected_delivery, total_price, notes, created_at, updated_at
`

type CreateJobParams struct {
	CustomerID         uuid.UUID      `json:"customer_id"`
	Status             JobStatus      `json:"status"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
}

// Creates a new job with an auto-generated job number (KW-0001 format).
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.CustomerID,
		arg.Status,
		arg.ExpectedCompletion,
		arg.ExpectedDelivery,
		arg.TotalPrice,
		arg.Notes,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.JobNumber,
		&i.Status,
		&i.ExpectedCompletion,
		&i.ExpectedDelivery,
		&i.TotalPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

// Permanently deletes a job and its structures (CASCADE).
func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.customer_id, j.job_number, j.status, j.expected_completion, j.expected_delivery, j.total_price, j.notes, j.created_at, j.updated_at, c.name AS customer_name
FROM jobs j
JOIN customers c ON c.id = j.customer_id
WHERE j.id = $1
`

type GetJobRow struct {
	ID                 uuid.UUID      `json:"id"`
	CustomerID         uuid.UUID      `json:"customer_id"`
	JobNumber          string         `json:"job_number"`
	Status             JobStatus      `json:"status"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CustomerName       string         `json:"customer_name"`
}

// Retrieves a single job with its customer name.
func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.JobNumber,
		&i.Status,
		&i.ExpectedCompletion,
		&i.ExpectedDelivery,
		&i.TotalPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
	)
	return i, err
}

const getKanbanJobs = `-- name: GetKanbanJobs :many
SELECT j.id, j.job_number, j.status, j.expected_completion, j.expected_delivery,
       j.total_price, j.notes, j.created_at, c.name AS customer_name
FROM jobs j
JOIN customers c ON c.id = j.customer_id
ORDER BY j.status, j.created_at
`

type GetKanbanJobsRow struct {
	ID                 uuid.UUID      `json:"id"`
	JobNumber          string         `json:"job_number"`
	Status             JobStatus      `json:"status"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	CustomerName       string         `json:"customer_name"`
}

// Retrieves all jobs with customer names for the kanban board view.
// Results are ordered by creation date within each status group.
func (q *Queries) GetKanbanJobs(ctx context.Context) ([]GetKanbanJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getKanbanJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetKanbanJobsRow{}
	for rows.Next() {
		var i GetKanbanJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobNumber,
			&i.Status,
			&i.ExpectedCompletion,
			&i.ExpectedDelivery,
			&i.TotalPrice,
			&i.Notes,
			&i.CreatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.customer_id, j.job_number, j.status, j.expected_completion, j.expected_delivery, j.total_price, j.notes, j.created_at, j.updated_at, c.name AS customer_name
FROM jobs j
JOIN customers c ON c.id = j.customer_id
ORDER BY j.created_at DESC
`

type ListJobsRow struct {
	ID                 uuid.UUID      `json:"id"`
	CustomerID         uuid.UUID      `json:"customer_id"`
	JobNumber          string         `json:"job_number"`
	Status             JobStatus      `json:"status"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CustomerName       string         `json:"customer_name"`
}

// Retrieves all jobs with customer names, newest first.
func (q *Queries) ListJobs(ctx context.Context) ([]ListJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.JobNumber,
			&i.Status,
			&i.ExpectedCompletion,
			&i.ExpectedDelivery,
			&i.TotalPrice,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT j.id, j.customer_id, j.job_number, j.status, j.expected_completion, j.expected_delivery, j.total_price, j.notes, j.created_at, j.updated_at, c.name AS customer_name
FROM jobs j
JOIN customers c ON c.id = j.customer_id
WHERE j.status = $1
ORDER BY j.created_at DESC
`

type ListJobsByStatusRow struct {
	ID                 uuid.UUID      `json:"id"`
	CustomerID         uuid.UUID      `json:"customer_id"`
	JobNumber          string         `json:"job_number"`
	Status             JobStatus      `json:"status"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CustomerName       string         `json:"customer_name"`
}

// Retrieves jobs filtered by status, with customer names.
func (q *Queries) ListJobsByStatus(ctx context.Context, status JobStatus) ([]ListJobsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByStatusRow{}
	for rows.Next() {
		var i ListJobsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.JobNumber,
			&i.Status,
			&i.ExpectedCompletion,
			&i.ExpectedDelivery,
			&i.TotalPrice,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET customer_id = $2, expected_completion = $3, expected_delivery = $4, total_price = $5, notes = $6
WHERE id = $1
RETURNING id, customer_id, job_number, status, expected_completion, expected_delivery, total_price, notes, created_at, updated_at
`

type UpdateJobParams struct {
	ID                 uuid.UUID      `json:"id"`
	CustomerID         uuid.UUID      `json:"customer_id"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
}

// Updates all editable fields on an existing job.
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.ID,
		arg.CustomerID,
		arg.ExpectedCompletion,
		arg.ExpectedDelivery,
		arg.TotalPrice,
		arg.Notes,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.JobNumber,
		&i.Status,
		&i.ExpectedCompletion,
		&i.ExpectedDelivery,
		&i.TotalPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET status = $2 WHERE id = $1 RETURNING id, customer_id, job_number, status, expected_completion, expected_delivery, total_price, notes, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status JobStatus `json:"status"`
}

// Updates only the status of a job (used by kanban drag-drop).
func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.JobNumber,
		&i.Status,
		&i.ExpectedCompletion,
		&i.ExpectedDelivery,
		&i.TotalPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
