// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type JobStatus string

const (
	JobStatusQuote      JobStatus = "quote"
	JobStatusInProgress JobStatus = "in_progress"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusDelivered  JobStatus = "delivered"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type JobStructureStatus string

const (
	JobStructureStatusPending    JobStructureStatus = "pending"
	JobStructureStatusInProgress JobStructureStatus = "in_progress"
	JobStructureStatusCompleted  JobStructureStatus = "completed"
)

func (e *JobStructureStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStructureStatus(s)
	case string:
		*e = JobStructureStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStructureStatus: %T", src)
	}
	return nil
}

type NullJobStructureStatus struct {
	JobStructureStatus JobStructureStatus `json:"job_structure_status"`
	Valid              bool               `json:"valid"` // Valid is true if JobStructureStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStructureStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStructureStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStructureStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStructureStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStructureStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Customer struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Job struct {
	ID                 uuid.UUID      `json:"id"`
	CustomerID         uuid.UUID      `json:"customer_id"`
	JobNumber          string         `json:"job_number"`
	Status             JobStatus      `json:"status"`
	ExpectedCompletion sql.NullTime   `json:"expected_completion"`
	ExpectedDelivery   sql.NullTime   `json:"expected_delivery"`
	TotalPrice         sql.NullString `json:"total_price"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type JobStructure struct {
	ID         uuid.UUID          `json:"id"`
	JobID      uuid.UUID          `json:"job_id"`
	TemplateID uuid.NullUUID      `json:"template_id"`
	CustomName sql.NullString     `json:"custom_name"`
	Quantity   int32              `json:"quantity"`
	UnitPrice  sql.NullString     `json:"unit_price"`
	Status     JobStructureStatus `json:"status"`
	Notes      sql.NullString     `json:"notes"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type StructureTemplate struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BasePrice   sql.NullString `json:"base_price"`
	Category    string         `json:"category"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	GoogleID  string    `json:"google_id"`
	Role      UserRole  `json:"role"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
