// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: structure_templates.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStructureTemplate = `-- name: CreateStructureTemplate :one
INSERT INTO structure_templates (name, description, base_price, category)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, base_price, category, created_at, updated_at
`

type CreateStructureTemplateParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BasePrice   sql.NullString `json:"base_price"`
	Category    string         `json:"category"`
}

// Creates a new structure template in the catalog.
func (q *Queries) CreateStructureTemplate(ctx context.Context, arg CreateStructureTemplateParams) (StructureTemplate, error) {
	row := q.db.QueryRowContext(ctx, createStructureTemplate,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.Category,
	)
	var i StructureTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStructureTemplate = `-- name: DeleteStructureTemplate :exec
DELETE FROM structure_templates WHERE id = $1
`

// Permanently deletes a structure template.
// Will fail if any job structures reference it (FK constraint).
func (q *Queries) DeleteStructureTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStructureTemplate, id)
	return err
}

const getStructureTemplate = `-- name: GetStructureTemplate :one
SELECT id, name, description, base_price, category, created_at, updated_at FROM structure_templates WHERE id = $1
`

// Retrieves a single structure template by ID.
func (q *Queries) GetStructureTemplate(ctx context.Context, id uuid.UUID) (StructureTemplate, error) {
	row := q.db.QueryRowContext(ctx, getStructureTemplate, id)
	var i StructureTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStructureTemplates = `-- name: ListStructureTemplates :many
SELECT id, name, description, base_price, category, created_at, updated_at FROM structure_templates ORDER BY category, name
`

// Retrieves all structure templates ordered by category then name.
func (q *Queries) ListStructureTemplates(ctx context.Context) ([]StructureTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listStructureTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StructureTemplate{}
	for rows.Next() {
		var i StructureTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStructureTemplate = `-- name: UpdateStructureTemplate :one
UPDATE structure_templates
SET name = $2, description = $3, base_price = $4, category = $5
WHERE id = $1
RETURNING id, name, description, base_price, category, created_at, updated_at
`

type UpdateStructureTemplateParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BasePrice   sql.NullString `json:"base_price"`
	Category    string         `json:"category"`
}

// Updates an existing structure template.
func (q *Queries) UpdateStructureTemplate(ctx context.Context, arg UpdateStructureTemplateParams) (StructureTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateStructureTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.Category,
	)
	var i StructureTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
